-- Mappools custom
create table if not exists public.mappool_collections (
  id bigint generated by default as identity primary key,
  title text not null,
  stage text null,
  accent_color text not null default '#a855f7',
  drive_url text null,
  created_at timestamptz not null default now()
);

create table if not exists public.mappool_items (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.mappool_collections(id) on delete cascade,
  beatmap_url text not null,
  mods text null,
  label_color text not null default '#a855f7',
  sort_order integer not null default 0,
  beatmap_id bigint null,
  title text null,
  artist text null,
  version text null,
  cover_url text null,
  star_rating numeric null,
  created_at timestamptz not null default now()
);

-- Bracket custom
create table if not exists public.bracket_nodes (
  id bigint generated by default as identity primary key,
  stage text null,
  scheduled_at timestamptz null,
  x integer not null default 0,
  y integer not null default 0,
  team1 text null,
  team2 text null,
  score1 integer not null default 0,
  score2 integer not null default 0,
  best_of integer not null default 9,
  current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.bracket_edges (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.bracket_nodes(id) on delete cascade,
  target_id bigint not null references public.bracket_nodes(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Auditoría staff
create table if not exists public.staff_audit_log (
  id bigint generated by default as identity primary key,
  actor_id bigint null,
  actor_role text null,
  action text not null,
  entity_type text null,
  entity_id text null,
  metadata jsonb null,
  created_at timestamptz not null default now()
);

-- Extensiones de noticias (programación / visibilidad)
alter table if exists public.news
  add column if not exists publish_at timestamptz null default now(),
  add column if not exists is_published boolean not null default true,
  add column if not exists is_hidden boolean not null default false;

-- Extensiones de mantenimiento (whitelist / plantilla / banner home)
alter table if exists public.site_settings
  add column if not exists maintenance_whitelist_text text null,
  add column if not exists maintenance_template text null default 'default',
  add column if not exists maintenance_banner_enabled boolean not null default true;

-- Home pública configurable (hero + roadmap + twitch)
create table if not exists public.homepage_settings (
  id bigint primary key,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
